name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.1"
      - name: Install dependencies
        run: Rscript scripts/setup_env.R
      - name: Run dryrun
        run: Rscript scripts/run_dryrun.R --sensor_id VG09 --date 2023-01-01
