name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      # Restore packages via renv with caching
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Run the dry run script (no setup_env.R here)
      - name: Dry run
        run: Rscript scripts/run_dryrun.R --sensor_id VG09 --date 2025-08-10

      - name: sessionInfo
        run: Rscript -e 'sessionInfo()'
