name: pkgdown
on:
  push:
    branches: [ "main" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      # Restore packages via renv with caching
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Build site into ./docs
      - name: Build pkgdown site
        run: |
          R -q -e 'devtools::document()'
          R -q -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'

      # Deploy (docs/ branch publishing)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
